### ISSUE TITLE
Navigation Drawer / Hamburger Button No Longer Works

### ISSUE THREAD

**Issue by FireJuun** [bnxm/material_floating_search_bar#29]
Upon upgrading to the latest stable version of Flutter (2.0.1), the previously functioning navigation drawer and the 'hamburger icon' on the search bar no longer works consistently.

Steps to recreate.
run `flutter create brokendrawer`

Update `pubspec.yaml` to include:

```yaml
dependencies:
...
  cupertino_icons: ^1.0.2
  http: ^0.13.0
  implicitly_animated_reorderable_list: ^0.3.2
  material_design_icons_flutter: ^4.0.5955
  material_floating_search_bar: ^0.2.6
  provider: ^5.0.0
...
  assets:
    - assets/map.jpg
```

Add `map.jpg` from the example repo to the assets folder, and copy `main.dart`, `place.dart`, and `search_model.dart` from the original repo to the lib folder. 

On iOS emulator, click on the hamburger icon on the left. It may or may not cause the Drawer() to open. See this GIF for an example:

![broken-nav-drawer](https://user-images.githubusercontent.com/45612810/110514519-5fe27c80-80d5-11eb-9ab0-252fafd52956.gif)
