### ISSUE TITLE
The FPS is very low when pull down the body in 0.3.3

### ISSUE THREAD

**Issue by simonkimi** [bnxm/material_floating_search_bar#33]
Hello! Thanks for upgrading to null safety!
But when I upgraded from 0.2.6 to 0.3.3, I found that the fps was a bit strange.

When I pull down the body,  I noticed that `builder` was called repeatedly like this.

![123](https://user-images.githubusercontent.com/49084387/113469873-a7191e80-9483-11eb-8db0-9c73b2ff8f7f.gif)
![图片](https://user-images.githubusercontent.com/49084387/113469897-cd3ebe80-9483-11eb-893e-cf1232df79b5.png)

But in 0.2.6, it works fine.
![456](https://user-images.githubusercontent.com/49084387/113469955-4807d980-9484-11eb-95de-c014fe6e5f29.gif)
![图片](https://user-images.githubusercontent.com/49084387/113469953-41796200-9484-11eb-8e79-940a7ae07e25.png)

Did i do something wrong?

Here is my code:
```dart
import 'package:flutter/material.dart';
import 'package:material_floating_search_bar/material_floating_search_bar.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: TestPage(),
    );
  }
}

class TestPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: FloatingSearchBar(
        transitionCurve: Curves.easeInOutCubic,
        transition: CircularFloatingSearchBarTransition(),
        physics: const BouncingScrollPhysics(),
        builder: (context, _) => buildBody(),
      ),
    );
  }

  Widget buildBody() {
    final time = DateTime.now();
    print('BuildBody at ${time.second}:${time.millisecond}');
    return ClipRRect(
      borderRadius: BorderRadius.circular(8),
      child: Material(
        child: Column(
          children: List.generate(100, (index) => index.toString())
              .map((e) => ListTile(
                    title: Text(e),
                  ))
              .toList(),
        ),
      ),
    );
  }
}
```

0.3.3:
```yml
name: searchbar_demo
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  material_floating_search_bar: ^0.3.3


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

```

0.2.6
```yml
name: searchbar_demo
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  material_floating_search_bar: ^0.2.6


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

```
